### ISSUE TITLE
Feature request: ignore retweets/boosts

### ISSUE THREAD

**Issue by kpcyrd** [klausi/mastodon-twitter-sync#11]
I'd like to ignore both retweets and boosts when syncing my accounts.

**Comment by klausi** [comment]
Yep, that would make sense. We could add a boolean config option "ignore_retweets" and "ignore_boosts" with a default value of false.

I don't plan to work on this but feel free to send a pull request!

**Comment by bajtos** [comment]
Thank you @klausi for this great tool ❤️

I opened a pull request to implement the two new options you described: https://github.com/klausi/mastodon-twitter-sync/pull/14. Can you please review?
