### ISSUE TITLE
Panic in main

### ISSUE THREAD

**Issue by ln5** [klausi/mastodon-twitter-sync#2]
First invocation, after entering twitter oauth PIN:

> Paste your PIN:
_<redacted>_
thread_ 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: mastodon_twitter_sync::main
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
  13: _start
  14: <unknown>

(And no, I couldn't find out how to render "colon" imp "colon" less colourful. :))

This is in a jail on FreeBSD 10.3 with rustc 1.22.1.
Please let me know how to provide further information.

**Comment by ln5** [comment]
FWIW, I've reproduced this on a Debian 9 (stretch) system with rustc 1.24.1.

One thing, possibly unrelated, that I find peculiar is that the authorization request to Twitter seems to be for read-only access.

**Comment by klausi** [comment]
Thanks a lot for reporting!

This seems to be a bug in the Rust TOML library when serializing configuration.

The workaround fix is to change the order of properties on your rust struct.

Twitter App: it needs read+write access, you can set that at `https://apps.twitter.com/app/<YOUR APP ID>/permissions`. I guess I should document that in the setup steps.

**Comment by ln5** [comment]
The fix solves the reported problem, thanks!

Re the permission, my _application_ has read and write but my _access_token_ has read-only. I can indeed change permissions for the app, but not for the token. I suspect that I could work around this by generating a new token from the web page and edit the mastodon-twitter-sync.toml file. I'd rather follow your instructions though.

LMK if you prefer a new ticket for this issue.

**Comment by klausi** [comment]
Yes, please open a new issue.

I didn't even know that access tokens can have permissions? I thought they just get the same permissions as the Twitter app has?
