### ISSUE TITLE
Bug: can't compile, unresolved import `mammut`

### ISSUE THREAD

**Issue by gregharvey** [klausi/mastodon-twitter-sync#30]
Hi,

Just a heads up that HEAD has a compiling issue with `mammut` at the moment. I'm on Fedora Linux using `cargo 1.45.0` and I get this:

```
   Compiling mastodon-twitter-sync v1.5.0 (/home/greg/workspace/github/mastodon-twitter-sync)
error[E0432]: unresolved import `mammut`
 --> src/main.rs:1:5
  |
1 | use mammut::{Mastodon, StatusesRequest};
  |     ^^^^^^ use of undeclared type or module `mammut`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `mastodon-twitter-sync`.

```

Note, v1.5.0 is fine, it's only HEAD that is affected. If I expressly checkout the v1.5.0 tag it compiles fine. You probably know already, but just in case. :-)

**Comment by klausi** [comment]
Hm, the master branch is passing on Travis CI. Maybe you have the wrong master branch checked out?

**Comment by gregharvey** [comment]
You're right, I merged in your master to my master but there must be something in mine that is borked. I need to rebase or something. When I checked out klausi/master and ran `cargo check` it was fine, so it's just me. Sorry about the false alarm!
