### ISSUE TITLE
Provide a binary with each release

### ISSUE THREAD

**Issue by mikebell** [klausi/mastodon-twitter-sync#38]
Would it be possible to provide a binary (Linux amd64) with each release?

I'm not familiar with Rust at all and would like to package it up in a container rather than having to install all the Rust dependencies.

**Comment by klausi** [comment]
Unfortunately not that easily because there is a dynamic link to openssl by some dependency last time I checked. Then the binary did not work on different Linux/OpenSSL versions.

But we could setup an Ubuntu 20.04 build job to attach to releases, better than nothing?

**Comment by mikebell** [comment]
Yeah that would work. I can look at including it in a docket container. Is
there a flag to pass the path to the config file?

**Comment by klausi** [comment]
There is not (yet?) - config file must be in the current working directory.

**Comment by klausi** [comment]
A lot of things improved:
* We have a docker container image now, check the README
* You can specify the path to the config file with `--config` 
* We eliminated the dependency to OpenSSL, so it should be possible to provide precompiled binaries with releases now. Will keep this issue open to work on that, should not be hard with https://github.com/taiki-e/upload-rust-binary-action

**Comment by klausi** [comment]
And I'm done! Binaries are now available on the release page.

They don't work on all platforms, for example the Linux binary only works on newer distributions. On an old Debian 9 I get the error
```
/home/klausi/mastodon-twitter-sync: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/klausi/mastodon-twitter-sync)
```
But I think we don't care, people can always compile themselves on older systems.

Please test and let me know if you see any problems!
