### ISSUE TITLE
Fail to build project after update

### ISSUE THREAD

**Issue by ekianjo** [klausi/mastodon-twitter-sync#39]
Hi there,
I have recently tried to upgrade to a more recent version of the source via a git pull, followed by a cargon --run release, and during compilation it fails with the following error (I'm on Debian Buster and my packages are up to date):

```
For more information about this error, try `rustc --explain E0658`.
error: could not compile `object`.
```
It also prints a bunch of errors such as:

```
error[E0658]: subslice patterns are unstable
```

Any idea what may be going on?

**Comment by klausi** [comment]
Hi, maybe you are using an old Rust compiler version?

Best update to the latest Rust version and test again.

**Comment by klausi** [comment]
We have now prebuilt binaries and a docker image, please use those.
