### ISSUE TITLE
called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by ln5** [klausi/mastodon-twitter-sync#4]
Seen the following three times the last couple of days:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
> value: Serde(ErrorImpl { code: ExpectedSomeValue, line: 1, column: 1
> })', src/libcore/result.rs:906:4

Unable to reproduce. Will try to get a backtrace. Anything else that can be of help here?

**Comment by ln5** [comment]
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Serde(ErrorImpl { code: ExpectedSomeValue, line: 1, column: 1 })', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: mastodon_twitter_sync::main
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
  13: _start
  14: <unknown>

**Comment by klausi** [comment]
Thanks for reporting! From your trace I cannot see the line number where stuff went wrong in main(). I added some more useful error messages to the API calls in main().

What you are seeing here are downtimes of the Mastodon API for whatever reason. We should file an issue upstream in https://github.com/Aaronepower/Mammut to have better error messages in case Mastodon is down.

**Comment by ln5** [comment]
Filed https://github.com/Aaronepower/Mammut/issues/28 to track this.
