### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by jurgenhaas** [klausi/mastodon-twitter-sync#40]
I've played around with it and got it working inside Docker with persistent post cache too. Here are the instructions on how that works:

# Build Docker image

Create a `Dockerfile` with this content:

```
FROM debian:10

RUN true \
    && apt-get update \
    && apt-get install git curl openssh-client build-essential libssl-dev pkg-config -y \
    && mkdir -p -m 0600 ~/.ssh \
    && ssh-keyscan github.com >> ~/.ssh/known_hosts \
    && curl https://sh.rustup.rs -o rustup \
    && chmod +x rustup \
    && ./rustup -y \
    && git clone https://github.com/klausi/mastodon-twitter-sync.git \
    && cd /mastodon-twitter-sync \
    && ~/.cargo/bin/cargo build --release

RUN true \
    && mv /mastodon-twitter-sync/target/release/mastodon-twitter-sync /usr/local/bin/ \
    && rm -rf /mastodon-twitter-sync \
    && rm -rf /root/.rustup \
    && rm -rf /root/.cargo \
    && rm -rf /root/.ssh \
    && rm -rf /root/.bashrc \
    && rm -rf /root/.profile

WORKDIR /data

ENTRYPOINT [ "/usr/local/bin/mastodon-twitter-sync" ]
```

and call `docker build -t local/mastodon-twitter-sync .` in the same directory. This will take a while, when completed, try it out with `docker run --rm local/mastodon-twitter-sync --version`, it should output `mastodon-twitter-sync 1.6.0`.

# Run it

Create an empty directory with the `mastodon-twitter-sync.toml` file in it and provide all your config data in it. You can then run it with this command:

```
docker run --rm -v "$(pwd)":/data local/mastodon-twitter-sync
```

and you can add any of the supported arguments to the command line.

The `post_cache.json` file is being written to the same directory on the host as well so that you can keep that even if your docker container ever got pruned and needed to be rebuilt.

**Comment by klausi** [comment]
This was done in #41
