### ISSUE TITLE
Update dependencies to support OpenSSL 1.1.1

### ISSUE THREAD

**Issue by ao2** [klausi/mastodon-twitter-sync#5]
Hi,

on Debian Unstable the default OpenSSL version is 1.1.1 and the openssl crate version 0.9.24 brought in by the current dependencies does not support it, so some dependency would need to be updated.

In particular compiling fails with this message:
```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/ao2/WIP/mastodon/mastodon-twitter-sync/Mammut/target/debug/build/openssl-3a8db21765a1c7e0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/ao2/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

For now I identified the issue in Mammut: https://github.com/Aaronepower/Mammut/issues/43

I'll look into egg-mode too.

I am not sure if the `Cargo.toml` in mastodon-twitter-sync needs to be changed as it uses `>=` for version numbers, but at least a `cargo update` would be needed so I opened this issue as a reminder.

Thanks,
   Antonio

**Comment by ao2** [comment]
Here is the egg-mode issue: https://github.com/QuietMisdreavus/twitter-rs/issues/48

**Comment by klausi** [comment]
Mammut update is done.

There is no egg-mode release yet, so hacking in the master branch somehow is the next step.

**Comment by klausi** [comment]
And updated egg-mode to the master branch, please test!

I think we are done here.
