### ISSUE TITLE
Can't it sync historic tweets do, but rate limit it if the API can't handle it otherwise?

### ISSUE THREAD

**Issue by Seyferto** [klausi/mastodon-twitter-sync#61]

**Comment by klausi** [comment]
It could, but is that useful? Your followers will not like you if you shove 5000 posts from you within the same minute into their timeline. They will probably unfollow you for spamming posts.

Or what do you mean by syncing historic tweets?

**Comment by Seyferto** [comment]
Followers are, really, not part of the equation here... I do mean that by historic tweets... but if it's rate-limited due to the APIs how would it be in the same minute? Post them every ten minutes, or such...

**Comment by orhun** [comment]
There is a 200 Tweet limit in [`egg_mode::tweet::user_timeline`](https://docs.rs/egg-mode/latest/egg_mode/tweet/fn.user_timeline.html):

> This method has a default page size of 20 tweets, with a maximum of 200. Note that asking to leave out replies or retweets will generate pages that may have fewer tweets than your requested page size; Twitter will load the requested number of tweets before removing replies and/or retweets.
> Twitter will only load the most recent 3,200 tweets with this method.

Just my 2 cents.

**Comment by Seyferto** [comment]
Is that a limit in total, forever?

**Comment by klausi** [comment]
Hm, I don't think it is useful to post my complete Twitter history to Mastodon over a period of time. Followers are a critical part of this consideration here, as we would serve them very old tweets that are out of time. How is it useful for you or them to present them for example tweets from 2015 as new Mastodon posts?

**Comment by Seyferto** [comment]
No one's forcing anyone to do anything? I merely request it as an option... and followers aren't an equation for me because I don't have any... I just want a backup... none of mine are time-critical...

**Comment by klausi** [comment]
I see, mastodon-twitter-sync is not meant to be used as backup tool. Implementing this option would raise the complexity of the code base for an edge case, so we will not consider implementing it at this time.

You can use the Twitter export functionality to make a backup: https://help.twitter.com/en/managing-your-account/accessing-your-twitter-data
Similar on Mastodon: https://docs.joinmastodon.org/user/moving/

Thanks for clarifying, I will close this feature request.

**Comment by Seyferto** [comment]
You did notice "Mastodon currently does not support importing posts"?

Frankly I've no idea what the point of your tool is... there's another one that has exactly the same functionality... one would hope there would be something extra, but I guess being clones is all that can be since apparently you personally don't have a use for it...
