### ISSUE TITLE
Issue with GIF/movies on some posts

### ISSUE THREAD

**Issue by A-Swafford** [klausi/mastodon-twitter-sync#63]
I get an error while moving some tweets over to toots. Specifically those with movies:
```
Posting to Mastodon: RT sshekhr: Using a stentor-pair as a model, we found that neighbors continuously change the separation between them! As the distance decreases, inner vortices fuse and the flow rate of the feeding flow increases! 5/n
Error posting toot to Mastodon: Error {
    context: "Failed downloading attachment ",
    source: reqwest::Error {
        kind: Builder,
        source: RelativeUrlWithoutBase,
    },
}
```

**Comment by A-Swafford** [comment]
Can confirm this affects multiple media types -- including links.
We present the acquisition and analysis of complete parental chromosomes from ALL public AMF heterokaryons.

This 3 year long endeavour survived my stroke, the loss of multiple DNA shipments and data (thx covid).

But we did it! 👇

https://biorxiv.org/cgi/content/short/2023.01.15.524[13](https://github.com/A-Swafford/mts-cron/actions/runs/3962780099/jobs/6789870284#step:8:14)8v1
Error posting toot to Mastodon: Error {
    context: "Failed downloading attachment ",
    source: reqwest::Error {
        kind: Builder,
        source: RelativeUrlWithoutBase,
    },
}

**Comment by klausi** [comment]
Thanks for reporting! Can you provide links to the tweets? Then we can debug what is special about them.

**Comment by A-Swafford** [comment]
Here's the link for one:
https://twitter.com/Blunt_Microbe/status/1616069504160731137?s=20
And the other:
https://twitter.com/sshekhr/status/1616043461710340097?s=20

**Comment by nfrankel** [comment]
In the meantime, is there anyway to bypass the issue besides deleting the tweet?

Sync is blocked...

**Comment by A-Swafford** [comment]
> In the meantime, is there anyway to bypass the issue besides deleting the tweet?
> 
> Sync is blocked...

Point is moot since twitter is removing API. but if you're paying for api access I have not found a workaround yet.

**Comment by klausi** [comment]
Fixed, thanks for reporting!
