### ISSUE TITLE
Writeout full Mastodon username

### ISSUE THREAD

**Issue by 9Lukas5** [klausi/mastodon-twitter-sync#64]
I just saw it in a synced Boost as well an answer in a thread where I mentioned someone: The crosspost to Twitter only holds the user part of the full Mastodon-Handle. This makes it hard to find that person in the Fediverse if someone is interested to do so, as the domain part is missing.

## Current Behavior:

Crossposts from Mastodon to Twitter with usernames are missing the domain part of the mentioned users

## Expected Behavior:

Crossposts from Mastodon to Twitter have the full username of mentioned users

**Comment by klausi** [comment]
Hi, thanks for reporting! I implemented the omission of mastodon server names on purpose for 2 reasons:
1. Save space, Twitter messages need to be short
2. Have better readability, as full mastodon host names with multiple mentions quickly get out of hand and unreadable

I think I will keep it this way. We could make it configurable to determine if you want to have full host names or not, but that would also increase code complexity and maintenance effort.

I will code this for now, if there is demand from more people in the future we can reconsider.

**Comment by 9Lukas5** [comment]
I'll respect your decision.
Nevertheless I'd like to point out that omitting the server part makes the user-handle incomplete and by that also ambiguous.

But thanks for the response :+1:

**Comment by davinkevin** [comment]
I would have like to get this feature FYI, sad to see it closed. 

The main interest for me is to make people on twitter able to know some are on mastodon… some kind of auto promotion 😇.

And having it the other way too, with @twitter.con for twitter handles, like https://github.com/renatolond/mastodon-twitter-poster already does.
