### ISSUE TITLE
Sync fails for media directly added to the tweet

### ISSUE THREAD

**Issue by nfrankel** [klausi/mastodon-twitter-sync#69]
[This tweet](https://twitter.com/nicolas_frankel/status/1620423298894172160) cannot be synchronized because it contains a GIF. I already had the same issue when I added an image directly to the tweet.

The error is:

```
Error posting toot to Mastodon: Error {
    context: "Failed downloading attachment ",
    source: reqwest::Error {
        kind: Builder,
        source: RelativeUrlWithoutBase,
    },
}
```

**Comment by klausi** [comment]
Thanks for reporting, I think this is a duplicate of #63

**Comment by nfrankel** [comment]
Sorry, I checked but I didn't see it.
