### ISSUE TITLE
Feature request: only sync on hashtag

### ISSUE THREAD

**Issue by gregharvey** [klausi/mastodon-twitter-sync#7]
Hi Klaus,

I'm really tempted to use this, but I wouldn't necessarily want to sync *everything* from Twitter to Mastodon, or vice versa. Would be really nice to be able to set a hashtag that triggers the sync, so the program only syncs tagged toots/tweets. :-)

Cheers,

Greg

**Comment by klausi** [comment]
Merged #24 , thanks!
