### ISSUE TITLE
crashes on attachment download

### ISSUE THREAD

**Issue by 9Lukas5** [klausi/mastodon-twitter-sync#70]
```log
Error posting toot to Mastodon: Error {
    context: "Failed downloading attachment ",
    source: reqwest::Error {
        kind: Builder,
        source: RelativeUrlWithoutBase,
    },
}
```

**Comment by klausi** [comment]
Thanks for reporting! Can you share a link the the problematic tweet or toot? Then we can maybe reproduce why that attachment download failed.

**Comment by 9Lukas5** [comment]
The Tweet was this one: https://twitter.com/V_Omelyan/status/1613260108145770496

And this link was in the log as well:
https://cfts.org.ua/news/2023/01/12/u_timchasovo_okupovanomu_mariupoli_zagarbniki_pochali_demontazh_tramvayno_koli_foto_73340
