### ISSUE TITLE
Feature request: only sync future tweets

### ISSUE THREAD

**Issue by kpcyrd** [klausi/mastodon-twitter-sync#9]
I'm thinking about syncing two accounts but I only want to sync things I post _after_ setting up the sync to avoid flooding my account with old content. Is there a good way to do that?

**Comment by klausi** [comment]
You can send a toot/tweet with the exact content from the other account. Then the program considers the 2 accounts to be in sync.

**Comment by kpcyrd** [comment]
I ended up implementing this in #10 :)

**Comment by klausi** [comment]
Thank you, #10 merged!
